### ISSUE TITLE
Dark mode context menu

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [X1pe0/NST#1]
Hey
I don't know if you're still working on this but...
having the tray icon menu be in dark mode would be pretty cool.

**Comment by X1pe0** [comment]
Hmm, give me a few days.

![preview](https://user-images.githubusercontent.com/9041120/212498894-3eefd9ca-a73a-4591-975a-0c6bb76ab924.PNG)

**Comment by X1pe0** [comment]
Damn, these few days have passed so quick... just added it lol. Enjoy
